### ISSUE TITLE
Bot replaces messages with webhooks when it shouldn't be

### ISSUE THREAD

**Issue by owlnai** [TheNozomi/ConfeBot#29]
One of the main features of the bot is automatically detecting wiktiext links and replacing them with a rich preview.

This has caused many problems lately, as shown in the image below. The bot deletes your message and replaces it with its own. Bot behavior should not limit the user, and in this case it seems inevitable for the server users unless a code change is made.
![image](https://user-images.githubusercontent.com/20427094/119206153-a6236700-ba9a-11eb-91cc-ce628093153e.png)

My proposal is that the bot should **only** delete messages on demand and not by default - and in any case, we're already using WikiBot on Confederación for the same behavior, why reinvent the wheel?

**Comment by TheNozomi** [comment]
I think the original idea of the link parser was to eventually replace Wiki-bot's features. But I agree it caused more harm than good, with this case being and example, and also when the message contains emojis. This should be discussed with the server staff, and then decide if remove the parser or change its behavior to match Wiki-bot's.
